#!/bin/bash

#
# XenServer specific defaults for the /tools/xen/ scripts
# Similar to stackrc, you can override these in your localrc
#

# Name of this guest
GUEST_NAME=${GUEST_NAME:-DevStackOSDomU}

# Template cleanup
CLEAN_TEMPLATES=${CLEAN_TEMPLATES:-false}

# Size of image
VDI_MB=${VDI_MB:-5000}
OSDOMU_MEM_MB=1024
OSDOMU_VDI_GB=8

# VM Password
GUEST_PASSWORD=${GUEST_PASSWORD:-secrete}

# Host Interface, i.e. the interface on the nova vm you want to expose the
# services on. Usually eth2 (management network) or eth3 (public network) and
# not eth0 (private network with XenServer host) or eth1 (VM traffic network)
HOST_IP_IFACE=${HOST_IP_IFACE:-eth3}

#
# Our nova host's network info
#

# A host-only ip that let's the interface come up, otherwise unused
VM_IP=${VM_IP:-10.255.255.255}
MGT_IP=${MGT_IP:-172.16.100.55}
PUB_IP=${PUB_IP:-192.168.1.55}

# Public network
PUB_NETMASK=${PUB_NETMASK:-255.255.255.0}
PUB_BR=${PUB_BR:-"xenbr0"}
PUB_VLAN=${PUB_VLAN:--1}
PUB_DEV=${PUB_DEV:-eth0}

# VM network params
VM_NETMASK=${VM_NETMASK:-255.255.255.0}
VM_BR=${VM_BR:-""}
VM_VLAN=${VM_VLAN:-100}
VM_DEV=${VM_DEV:-eth0}

# MGMT network params
MGT_NETMASK=${MGT_NETMASK:-255.255.255.0}
MGT_BR=${MGT_BR:-""}
MGT_VLAN=${MGT_VLAN:-101}
MGT_DEV=${MGT_DEV:-eth0}

# Decide if you should enable eth0,
# the guest installer network
# You need to disable this on xcp-xapi on Ubuntu 12.04
ENABLE_GI=true

# Ubuntu install settings
UBUNTU_INST_RELEASE="oneiric"
UBUNTU_INST_TEMPLATE_NAME="Ubuntu 11.10 (64-bit) for DevStack"
# For 12.04 use "precise" and update template name
# However, for 12.04, you should be using
# XenServer 6.1 and later or XCP 1.6 or later
# 11.10 is only really supported with XenServer 6.0.2 and later
UBUNTU_INST_ARCH="amd64"
UBUNTU_INST_HTTP_HOSTNAME="archive.ubuntu.net"
UBUNTU_INST_HTTP_DIRECTORY="/ubuntu"
UBUNTU_INST_HTTP_PROXY=""
UBUNTU_INST_LOCALE="en_US"
UBUNTU_INST_KEYBOARD="us"
# network configuration for ubuntu netinstall
UBUNTU_INST_IFACE="eth3"
UBUNTU_INST_IP="dhcp"
UBUNTU_INST_NAMESERVERS=""
UBUNTU_INST_NETMASK=""
UBUNTU_INST_GATEWAY=""

source ../../stackrc
