- nodeset:
    name: openstack-single-node
    nodes:
      - name: controller
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: openstack-two-node
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: compute1
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller
      - name: compute
        nodes:
          - controller
          - compute1
      - name: subnode
        nodes:
          - compute1

- job:
    name: devstack
    parent: multinode
    description: Base devstack job
    nodeset: openstack-single-node
    required-projects:
      - openstack-dev/devstack
      - openstack/cinder
      - openstack/glance
      - openstack/keystone
      - openstack/neutron
      - openstack/nova
      - openstack/requirements
      - openstack/swift
    roles:
      - zuul: openstack-infra/devstack-gate
      - zuul: openstack-infra/openstack-zuul-jobs
    timeout: 7200
    vars:
      test_matrix_configs: ['neutron', 'tlsproxy']
      devstack_localrc:
        DATABASE_PASSWORD: secretdatabase
        RABBIT_PASSWORD: secretrabbit
        ADMIN_PASSWORD: secretadmin
        SERVICE_PASSWORD: secretservice
        NETWORK_GATEWAY: 10.1.0.1
        Q_USE_DEBUG_COMMAND: true
        FIXED_RANGE: 10.1.0.0/20
        IPV4_ADDRS_SAFE_TO_USE: 10.1.0.0/20
        FLOATING_RANGE: 172.24.5.0/24
        PUBLIC_NETWORK_GATEWAY: 172.24.5.1
        FLOATING_HOST_PREFIX: 172.24.4
        FLOATING_HOST_MASK: 23
        SWIFT_REPLICAS: 1
        SWIFT_START_ALL_SERVICES: false
        SWIFT_HASH: 1234123412341234
        LOGFILE: /opt/stack/logs/devstacklog.txt
        LOG_COLOR: false
        VERBOSE: true
        NOVNC_FROM_PACKAGE: true
        ERROR_ON_CLONE: true
        # Gate jobs can't deal with nested virt. Disable it.
        LIBVIRT_TYPE: qemu
        # NOTE(dims): etcd 3.x is not available in debian/ubuntu
        # etc. As a stop gap measure, devstack uses wget to download
        # from the location below for all the CI jobs.
        ETCD_DOWNLOAD_URL: http://tarballs.openstack.org/etcd/
      devstack_services:
        horizon: false
        tempest: false
    pre-run: playbooks/pre.yaml
    run: playbooks/devstack.yaml
    post-run: playbooks/post.yaml

- job:
    name: devstack-multinode
    parent: devstack
    description: Base devstack multinode job
    nodeset: openstack-two-node
    # NOTE(andreaf) The multinode job is useful to see the setup of different
    # services on different nodes, however the subnode configuration is not
    # ready yet. Until then this job should stay non-voting.
    voting: false

- project:
    name: openstack-dev/devstack
    check:
      jobs:
        - devstack
        - devstack-multinode
