- nodeset:
    name: openstack-single-node
    nodes:
      - name: controller
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller

- nodeset:
    name: openstack-two-node
    nodes:
      - name: controller
        label: ubuntu-xenial
      - name: compute1
        label: ubuntu-xenial
    groups:
      - name: tempest
        nodes:
          - controller
      - name: compute
        nodes:
          - controller
          - compute1

- job:
    name: devstack
    parent: multinode
    description: Base devstack job
    nodeset: openstack-single-node
    required-projects:
      - openstack-dev/devstack
      - openstack/cinder
      - openstack/glance
      - openstack/keystone
      - openstack/neutron
      - openstack/nova
      - openstack/requirements
      - openstack/swift
    timeout: 7200
    vars:
      devstack_localrc:
        DATABASE_PASSWORD: secretdatabase
        RABBIT_PASSWORD: secretrabbit
        ADMIN_PASSWORD: secretadmin
        SERVICE_PASSWORD: secretservice
        NETWORK_GATEWAY: 10.1.0.1
        Q_USE_DEBUG_COMMAND: True
        FIXED_RANGE: 10.1.0.0/20
        IPV4_ADDRS_SAFE_TO_USE: 10.1.0.0/20
        FLOATING_RANGE: 172.24.5.0/24
        PUBLIC_NETWORK_GATEWAY: 172.24.5.1
        FLOATING_HOST_PREFIX: 172.24.4
        FLOATING_HOST_MASK: 23
        SWIFT_REPLICAS: 1
        SWIFT_START_ALL_SERVICES: False
        LOGFILE: /opt/stack/logs/devstacklog.txt
        LOG_COLOR: False
        VERBOSE: True
        NETWORK_GATEWAY: 10.1.0.1
        NOVNC_FROM_PACKAGE: True
        ERROR_ON_CLONE: True
        # Gate jobs can't deal with nested virt. Disable it.
        LIBVIRT_TYPE: qemu
        # NOTE(dims): etcd 3.x is not available in debian/ubuntu
        # etc. As a stop gap measure, devstack uses wget to download
        # from the location below for all the CI jobs.
        ETCD_DOWNLOAD_URL: "http://tarballs.openstack.org/etcd/"
      devstack_services:
        horizon: False
        tempest: False
    pre-run: playbooks/pre
    run: playbooks/devstack
    post-run: playbooks/post


- project:
    name: openstack-dev/devstack
    check:
      jobs:
        - devstack
