#!/bin/bash
#
# lib/os_brick
# Install **os-brick** python module from source

# Dependencies:
#
# - functions
# - DEST, DATA_DIR must be defined

# stack.sh
# ---------
# - install_os_brick

# Save trace setting
_XTRACE_OS_BRICK=$(set +o | grep xtrace)
set +o xtrace


GITDIR["os-brick"]=$DEST/os-brick

# Install os_brick from git only if requested, otherwise it will be pulled from
# pip repositories by requirements of projects that need it.
function install_os_brick {
    if use_library_from_git "os-brick"; then
        git_clone_by_name "os-brick"
        setup_dev_lib "os-brick"
    fi
}

# Restore xtrace
$_XTRACE_OS_BRICK