#!/bin/bash
#
# lib/oslo
#
# Functions to install **Oslo** libraries from git
#
# We need this to handle the fact that projects would like to use
# pre-released versions of oslo libraries.
#
# Included for compatibility with grenade, remove in Queens
source $TOP_DIR/lib/libraries
